### PR TITLE
ROX-11331: update nvdtools to fix cvss3 equation

### PR DESCRIPTION
**Pull request by RTann**
The latest version of nvdtools fixes the cvss3 equation to correctly determine a CVSS score of 0.0. This may affect CVSS scores for vulns in Scanners in the wild

### CODE REVIEW

**Comment by connorgorman** [comment]
Please make sure we see how many vulns are impacted by this and how many updates this will force

**Review by connorgorman — APPROVED** [review]

**Comment by connorgorman** [comment]
@RTann We should probably ship this one soon?

**Comment by RTann** [comment]
> @RTann We should probably ship this one soon?

Wanted to do the vuln analysis you suggested before but hadn't had the time for it. Will do that today. I don't expect this to affect many vulns, as this is for a base score of 0, which I think should be rare

**Comment by RTann** [comment]
Looks negligible to me, so going to merge:
```
rtannenb:~/go/src/github.com/stackrox/scanner$ cat new.json | jq '.[].Metadata.NVD.CVSSv3.Score' | grep -io "0" | wc -l
   97718
rtannenb:~/go/src/github.com/stackrox/scanner$ cat old.json | jq '.[].Metadata.NVD.CVSSv3.Score' | grep -io "0" | wc -l
   97709
rtannenb:~/go/src/github.com/stackrox/scanner$ cat new.json | jq '.[].Metadata.NVD.CVSSv2.Score' | grep -io "0" | wc -l
   25333
rtannenb:~/go/src/github.com/stackrox/scanner$ cat old.json | jq '.[].Metadata.NVD.CVSSv2.Score' | grep -io "0" | wc -l
   25333
rtannenb:~/go/src/github.com/stackrox/scanner$ cat new.json | jq '.[].Metadata["Red Hat"].CVSSv3.Score' | grep -io "0" | wc -l
    8188
rtannenb:~/go/src/github.com/stackrox/scanner$ cat old.json | jq '.[].Metadata["Red Hat"].CVSSv3.Score' | grep -io "0" | wc -l
    8178
rtannenb:~/go/src/github.com/stackrox/scanner$ cat new.json | jq '.[].Metadata["Red Hat"].CVSSv2.Score' | grep -io "0" | wc -l
   16318
rtannenb:~/go/src/github.com/stackrox/scanner$ cat old.json | jq '.[].Metadata["Red Hat"].CVSSv2.Score' | grep -io "0" | wc -l
   16318
```

**Pull request merged**
