### PR TITLE
Add runAsNonRoot to pod's security context

### PR DESCRIPTION
**Pull request by RTann**
Let the kubelet validate the image does not run as UID 0 (root). Putting this in the pod's security context means it applies to all containers in the pod (anything in a specific container's security context will take precedence).

By adding this, we cannot use named user/group for the `USER` field in the Dockerfiles, so this also reverts `USER postgres:postgres` back to `USER 70:70`

Also move the `runAsGroup` and `runAsUser` to the pod-level, as the two containers have the same security context, otherwise.

### CODE REVIEW

**Comment by RTann** [comment]
@msugakov the CI run for the first commit (https://github.com/stackrox/scanner/pull/793/commits/9c1ba86f2a70505e2e2525184f0d8645715c7dcb) seems to have been able to deploy Scanner and Scanner DB just fine without changing the Dockerfile?

**Review by msugakov — APPROVED** [review]

**Comment by msugakov** [comment]
@RTann I don't know why that run worked. Unfortunately there are no yaml dumps of resources to see if things were correctly applied.

**Comment by msugakov** [comment]
The problem is that describe output is not the same as `kubectl get pod ... -o yaml` output. The latter is more rich.
I suspect the issue did not occur here since you provided numeric user and group ids right in `securityContext`. Maybe in my experiment I did not have that and k8s relied on user/group from the Dockerfile.
I will take a look but most likely tomorrow because I'm in the final meeting for today.

**Comment by msugakov** [comment]
Yes, it was most likely that what I just wrote
https://github.com/stackrox/stackrox/blob/372b7a04e3efc8cd64386055f79d61d4c96a5a68/operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml#L815-L816

I guess it's up to you if you want to go back to `USER postgres:postgres` in the `Dockerfile`.

**Pull request merged**
