### PR TITLE
e2e: migrate GCR image to Quay

### PR DESCRIPTION
**Pull request by RTann**

### CODE REVIEW

**Comment by RTann** [comment]
CI failures are unrelated

**Comment by stehessel** [comment]
Do you need to change https://github.com/stackrox/stackrox/blob/master/scanner/e2etests/testdata/image_tests.json#L46 as well?

**Comment by RTann** [comment]
> Do you need to change https://github.com/stackrox/stackrox/blob/master/scanner/e2etests/testdata/image_tests.json#L46 as well?

Already have a PR here: https://github.com/stackrox/stackrox/pull/10286

**Review by stehessel — APPROVED** [review]
LGTM, confirmed that the image digest is identical.

**Pull request merged**
