### PR TITLE
build: Add Konflux pipeline activation through a label

### PR DESCRIPTION
**Pull request by msugakov**
Once PR is created with some branch name, it may be handy to enable Konflux builds on demand.

Inspiration from <https://pipelinesascode.com/docs/guide/authoringprs/#using-the-body-and-headers-in-a-pipelines-as-code-parameter> and <https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions>.

### CODE REVIEW

**Comment by msugakov** [comment]
Figured that `body.pull_request.labels` look the following way:
```json
    "labels": [
      {
        "color": "ededed",
        "default": false,
        "id": 4164972636,
        "name": "do-not-merge/work-in-progress",
        "node_id": "LA_kwDODLkO9s74QHBc",
        "url": "https://api.github.com/repos/stackrox/scanner/labels/do-not-merge/work-in-progress"
      },
      {
        "color": "D55C85",
        "default": false,
        "description": "Tells (Konflux) Renovate bot to calm down and not send more updates to this PR.",
        "id": 6987805440,
        "name": "stop-updating",
        "node_id": "LA_kwDODLkO9s8AAAABoIFzAA",
        "url": "https://api.github.com/repos/stackrox/scanner/labels/stop-updating"
      },
      {
        "color": "B0FE49",
        "default": false,
        "description": "Enable Konflux builds in this PR",
        "id": 7304553284,
        "name": "konflux-build",
        "node_id": "LA_kwDODLkO9s8AAAABs2KjRA",
        "url": "https://api.github.com/repos/stackrox/scanner/labels/konflux-build"
      }
    ],
```

**Comment by tommartensen** [comment]
Is the pipeline also triggered when you add or remove the label? From what I can see in the history of this PR, you added the label, then pushed https://github.com/stackrox/scanner/pull/1593/commits/53b0dcc45ba26d795cd65af8fe45687988b0883f, for which Konflux started to run.

**Comment by msugakov** [comment]
The pipeline does not start after I just add the label. Something needs to be committed to the PR branch. This works similar to our existing labels in stackrox project.

**Comment by tommartensen** [comment]
> The pipeline does not start after I just add the label. Something needs to be committed to the PR branch. This works similar to our existing labels in stackrox project.

GHA and OSCI can be triggered just by adding the label, e.g. `backport release-4.5` labels work like that. 
might be a question for #konflux-users.

**Comment by msugakov** [comment]
Following up here https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1723107909357619

**Review by tommartensen — APPROVED** [review]

**Pull request merged**
