### PR TITLE
Update redhatrelease to detect Alma Linux and have osrelease ignore it

### PR DESCRIPTION
**Pull request by msierks**
Update redhatrelease to detect Alma Linux and have osrelease ignore it.

### CODE REVIEW

**Review by RTann — APPROVED** [review]

**Comment by RTann** [comment]
@msierks because #745 was just merged, there is now a merge conflict. Would you mind resolving that? I can merge this once that's done, thanks!

**Comment by porridge** [comment]
@msierks looks like the last CI run failed. A lot has changed in our CI setup so a simple retry will not work I'm afraid? Would you mind rebasing and pushing your change?

**Pull request closed without merging**
