### PR TITLE
Update stackrox/stackrox dependency

### PR DESCRIPTION
**Pull request by RTann**
Our dependency was a bit dated, which, from a functionality standpoint, is ok, but this will also resolve vulnerabilities which have since been patched in dependencies.

### CODE REVIEW

**Comment by RTann** [comment]
Verified if we were to update the version of scanner in stackrox's go.mod there will be no dependency issues.

**Review by misberner — COMMENTED** [review]
In stackrox/stackrox, I once added an `exclude` directive to break the cycle of dependencies early, just to give `go mod tidy` less work. It's possible that this is no longer required in a newer go version - can you check whether adding `exclude github.com/stackrox/scanner <version imported by respective rox version>` has any material impact on the runtime of `go mod tidy` or the size of `go.sum`?

**Comment by RTann** [comment]
@misberner I added `exclude github.com/stackrox/scanner v0.0.0-20220426001230-9ab6777c9581` to my go.mod just now, and I saw no change to the go.sum. I also searched the go.sum file for any reference to `scanner`, but I did not find anything, so it looks like adding the `exclude` doesn't do much

**Review by misberner — APPROVED** [review]
Yeah LG. The go folks added some module pruning to the resolution algorithm in 1.16 or 1.17, that's probably it.

**Pull request merged**
