### PR TITLE
Update osrelease and redhatrelease detectors to detect Rocky Linux as…

### PR DESCRIPTION
**Pull request by msierks**
Update osrelease and redhatrelease detectors to detect Rocky Linux as well.

### CODE REVIEW

**Review by shahdeys — APPROVED** [review]

**Comment by msierks** [comment]
@RTann Any movement on this one?

**Comment by msugakov** [comment]
I added Ross as reviewer here so that he gets a notification email.

**Review by RTann — APPROVED** [review]

**Comment by RTann** [comment]
@msierks rebase/merge with the master branch, so CI can run on this PR :)

**Comment by msierks** [comment]
> @msierks rebase/merge with the master branch, so CI can run on this PR :)

@RTann This branch has been rebased with master.

**Comment by msierks** [comment]
@RTann The CI has passed on this one.

**Review by RTann — APPROVED** [review]

**Pull request merged**
